# Site settings
title: The Salon Expo
email: thesalonexpo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Salon Expo is a top of the line salon in Englewood, NJ.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: The Salon Expo
email: thesalonexpo@gmail.com
facebook_username: TheSalonExpo
twitter_username: thesalonexpo
github_username: thesalonexpo
yelp_bizname: the-salon-expo-englewood
instagram_username: thesalonexpo
address:
  - line: 76 W Palisade Ave.
  - line: Englewood, New Jersey, 07631
  # Feel free to add more lines here
telephone: (201) 569-4409
copyright: TheSalonExpo
styleseat:
  url: https://www.styleseat.com/v/
  salon_url: https://www.styleseat.com/m/book/s/thesalonexpo-englewood6-nj

# API settings
google_api_key:

# Build settings
markdown: kramdown
