# Site settings
title: The Salon Expo
description: > # this means to ignore newlines until "baseurl:"
  The Salon Expo is a top of the line salon in Englewood, NJ.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://TheSalonExpo.com" # the base hostname & protocol for your site

# User setting
owner: The Salon Expo
email: thesalonexpo@gmail.com
facebook_username: TheSalonExpo
twitter_username: thesalonexpo
github_username: thesalonexpo
yelp_bizname: the-salon-expo-englewood
instagram_username: thesalonexpo
hours:
  - line: "Mon-Wed: 10am-7pm"
  - line: "Thurs-Sat: 9am-8pm"
  - line: "Sunday: 10am-3pm"
address:
  - line: 76 W Palisade Ave.
  - line: Englewood, New Jersey, 07631
  # Feel free to add more lines here
telephone: (201) 569-4409
telephone_link: 201-569-4409
copyright: TheSalonExpo

# VENDOR -------------------------
vendor:
  name: phone

styleseat:
  url: https://www.styleseat.com/v/
  book_url: https://www.styleseat.com/m/book/v/
  salon_url: https://www.styleseat.com/m/book/s/thesalonexpo-englewood6-nj

booksy:
  url: http://thesalonexpo.booksy.com
  book_url: https://www.styleseat.com/m/book/v/
  salon_url: https://www.styleseat.com/m/book/s/thesalonexpo-englewood6-nj
# /VENDOR -------------------------

team:
  - employee:
    name: Johnny
    img: johnny.jpg
    styleseat_url: johnnymo
    info:
      position: Barber
      specialties: Men and Children cuts
  - employee:
    name: Nelson
    img: nelson.jpg
    styleseat_url: nelsonmolina
    info:
      position: Professional Hair Stylist
      specialties: Long Haircuts and Color
  - employee:
    name: Richard
    img: richard.jpg
    styleseat_url: richardhurtado
    info:
      position: Barber
      specialties: Barbering and Threading
  - employee:
    name: Danny
    img: danny.jpg
    work_num_link: 201-569-4409
    info:
      position: Barber
      specialties: Men and Children cuts
  - employee:
    name: Gustavo
    #img_placehold: true
    img: gustavo.jpg
    work_num_link: 201-569-4409
    info:
      position: Professional Hair Stylist
      specialties: Color and Highlights
  - employee:
    name: Minerva
    img: minerva.jpg
    styleseat_url: minervalantigua
    info:
      position: Professional Hair Stylist
      specialties: Curly Hair
  - employee:
    name: Areli
    img: areli.jpg
    styleseat_url: arelimunguia
    info:
      position: Professional Cosmotologist
      specialties: Manicure and Pedicure
  - employee:
    name: Patricia
    img: patricia.jpg
    styleseat_url: patriciagomez2
    info:
      position: Professional Cosmotologist
      specialties: Manicure and Pedicure
  - employee:
    name: Alejandra
    img: alejandra.jpg
    styleseat_url: alejandramarin
    info:
      position: Manicurist
      specialties: Children Manicure and Pedicure
  # - employee:
  #   name: Noel
  #   img_placehold: true
  #   work_num_link: 201-569-4409
  #   info:
  #     position: Barber
  #     specialties: Men Fades and Shape ups
  # - employee:
  #   name: Sam
  #   img: sam.jpg
  #   styleseat_url: sam
  #   info:
  #     position: Barber
  #     specialties: Fades and Beards
  
salon_specials:
  available: false
  info:
    name: Halloween
    class: creepster
    text:
      - line: Halloween Makeup
    img:
    cta:
      text: Book Now!
      url: https://www.styleseat.com/m/book/p/1202723



# API settings
google_api_key: AIzaSyCqWFE4rQFKvlE7YPMqC4WTi0Sd9eeiVDI

# Build settings
markdown: kramdown
