# Site settings
title: The Salon Expo
email: thesalonexpo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Salon Expo is a top of the line salon in Englewood, NJ.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: The Salon Expo
email: thesalonexpo@gmail.com
facebook_username:
twitter_username:
github_username:
address:
  - line: Englewood, New Jersey
  - line:
  # Feel free to add more lines here
telephone: 201 569-4409
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
