# Site settings
title: The Salon Expo
email: thesalonexpo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Salon Expo is a top of the line salon in Englewood, NJ.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://TheSalonExpo.com" # the base hostname & protocol for your site

# User setting
owner: The Salon Expo
email: thesalonexpo@gmail.com
facebook_username: TheSalonExpo
twitter_username: thesalonexpo
github_username: thesalonexpo
yelp_bizname: the-salon-expo-englewood
instagram_username: thesalonexpo
address:
  - line: 76 W Palisade Ave.
  - line: Englewood, New Jersey, 07631
  # Feel free to add more lines here
telephone: (201) 569-4409
copyright: TheSalonExpo
styleseat:
  url: https://www.styleseat.com/v/
  salon_url: https://www.styleseat.com/m/book/s/thesalonexpo-englewood6-nj

team:
  - employee:
    name: Richard
    img: richard.jpg
    styleseat_url: richardhurtado
    info:
      position: Master Barber
      specialties: Barbering and Threading
  - employee:
    name: Alejandra
    img: alejandra.jpg
    styleseat_url: alejandramarin
    info:
      position: Professional Cosmotologist
      specialties: Children Manicure and Pedicure
  - employee:
    name: Minerva
    img: minerva.jpg
    styleseat_url: minervalantigua
    info:
      position: Professional Hair Stylist
      specialties: Curly Hair
  - employee:
    name: Nelson
    img: nelson.jpg
    styleseat_url: neslonmolina
    info:
      position: Professional Hair Stylist
      specialties: Long Haircuts and Color
  - employee:
    name: Sandro
    img: sandro.jpg
    styleseat_url: sandro2
    info:
      position: Professional Hair Stylist and Barber
      specialties: Short Haircuts and Color
  - employee:
    name: Areli
    img: areli.jpg
    styleseat_url: arelimunguia
    info:
      position: Professional Cosmotologist
      specialties: Manicure and Pedicure
  - employee:
    name: Patricia
    img: patricia.jpg
    styleseat_url: patriciagomez2
    info:
      position: Professional Cosmotologist
      specialties: Manicure and Pedicure

# API settings
google_api_key: AIzaSyBl6ZstLuE6kgyqY4uZNFEZUIxu9W0uE3Y

# Build settings
markdown: kramdown
